name: env
channels:
- conda-forge
dependencies:
- lammps =2021.02.10=*openmpi*_4
- python =3.9
- pyiron =0.4.3
- nglview =2.7.7
- scikit-learn =1.0.1
- seaborn =0.11.1
- pyiron_base=0.4.2
- jupyter_client=7.0.6
- pyiron_atomistics=0.2.29
